# Select the language you wish to use, if selected language is not supported
# than it will default to english (the default being en)
language: en
logging:
  # To set whether logging is enabled (true or false)
  enabled: false
  database:
    #mysql is only option right now
    type: mysql
    # The Password to your Database
    password: password
    # The username to your Database
    username: username
    # The name of your database
    dbname: databasename
    # The url to your datanase, should be run on the same machine (localhost)
    url: some.url.should.be.localhost
    # The port your mysql server listens on (default: 3306)
    port: 3306
# Set the default limits of the server
# The old limits.yml is being phased out
defaults:
                   trader:
                     limits:
                       category: 3
                       levelcost:
                         '1': 1000
                         '2': 10000
                         '3': 15000
                         '4': 30000
                       createshop: 1000
                       createlevel: 1
                       enableremote: false
                       remoteitemcost: 500
                       itemactivatecost: 10000
                       maxshops: 1
                       maxlevel: 1